#import "@preview/ccicons:1.0.1": *

#align(bottom)[
  

© 2025 Hugo Ledoux, Ken Arroyo Ohori, Ravi Peters, and Maarten Pronk

#v(1cm)

#cc-by This work is available under a Creative Commons Attribution 4.0
International Licence. For licence details, see
#link("http://creativecommons.org/licenses/by/4.0/")

#table(
  stroke: none,
  inset: 3pt,
  columns: 2,
  align: (left, left),
  [`v2025.0`], [`[2025–10–27]`],
  [`v2024.0`], [`[2024–10–29]`],
  [`v2023.0`], [`[2023–11–12]`],
  [`v0.9`],    [`[2022–11–14]`],
  [`v0.8`],    [`[2021–11–08]`],
  [`v0.7`],    [`[2020–11–09]`],
  [`v0.6`],    [`[2019–11–11]`],  
) 

#strong[Download latest version] \
The latest version of this book can be downloaded in PDF at \
#link("https://github.com/tudelft3d/terrainbook/releases")

#strong[Extra material] \
Most chapters have a short YouTube video explaining the key concepts,
and some chapters have extra material. Available at \
#link("https://tudelft3d.github.io/terrainbook/videos")

#strong[Source code] \
The source code of the book, in LaTeX, is available at \
#link("https://github.com/tudelft3d/terrainbook")

#strong[Errors? Feedback?] \
Please report errors or potential improvements at \
#link("https://github.com/tudelft3d/terrainbook/issues")

#strong[Colophon] \
This book was typeset with LaTeX~using the
#link("https://github.com/fmarotta/kaobook")[`kaobook`] class. The
figures were created using Ipe, OmniGraffle, Affinity Designer, or
Blender. The front cover images was generated by DALL·E 3, and we made
some custom colour changes.

]
